#!/bin/bash

# Fail fast
set -o errexit

substep "Checking 1password agent symlink"
SSHSYMLINK=~/.1password/agent.sock
if [ ! -L "${SSHSYMLINK}" ]; then
  substep "Creating 1Password agent symlink"
  mkdir -p ~/.1password && ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock "${SSHSYMLINK}"
fi
substep_done "Checking 1password agent symlink ➡ complete"

substep "Configure .ssh/config"
ssh_config="Host *
IdentityAgent ~/.1password/agent.sock"
append_to_file "$ssh_config" "${HOME}"/.ssh/config
substep_done "Configure .ssh/config ➡ complete"

substep "Configure Git"
git config --global gpg.ssh.program "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
substep_done "Configure Git ➡ complete"
