#!/bin/bash

source_if_present() {
  local file="$1"
  # shellcheck disable=SC1090
  [[ -f "${file}" ]] && source "${file}"
}

CONFIG_BASE="${HOME}/.fettle-it/customisations"

# Load Customisations for all shells
source_if_present "${CONFIG_BASE}/env"
source_if_present "${CONFIG_BASE}/functions"
source_if_present "${CONFIG_BASE}/aliases"
source_if_present "$(brew --prefix)/etc/profile.d/autojump.sh"

# Load Shell-specific customisations
if [[ -n ${BASH} ]]; then
  source_if_present "${CONFIG_BASE}/bash/custom"
elif [[ -n ${ZSH_NAME} ]]; then
  source_if_present "${CONFIG_BASE}/zsh/custom"
  source_if_present "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

#if [[ -n $SSH_CONNECTION ]]; then
#  export EDITOR='vim'
#else
#  case "$(uname)" in
#    "Darwin")
#      export EDITOR='nvim'
#      # Setup iTerm2 tab names
#      export PROMPT_COMMAND='echo -ne "\\033]0;$(basename ${PWD/#$HOME/~})\\007"'
#      ;;
#    "Linux")
#      export EDITOR='gvim -f'
#      ;;
#    *)
#      export EDITOR='vim'
#      ;;
#  esac
#fi
