# vim:ft=yaml
# $XDG_CONFIG_HOME/k9s/hotkeys.yaml
hotKeys:
  shift-0:
    shortCut:    Shift-0
    description: Completed
    command:     pods /completed

  shift-1:
    shortCut:    Shift-1
    description: Failed
    command:     pods /failed
