#!/bin/bash

# Fail fast
set -o errexit

for file in $(git diff --name-only); do
  shfmt --diff -i 2 -sr -ci -w "${file}"
  if [ $? -ne 0 ]; then
    echo "shfmt failed on file '${file}'"
    exit 1
  else
    git add "${file}"
  fi
done
