#!/bin/bash

# Fail fast
set -o errexit

# Pretty colours
BLACK="$(tput setaf 0)"
BLACK_BG="$(tput setab 0)"
RED="$(tput setaf 1)"
RED_BG="$(tput setab 1)"
GREEN="$(tput setaf 2)"
GREEN_BG="$(tput setab 2)"
YELLOW="$(tput setaf 3)"
YELLOW_BG="$(tput setab 3)"
BLUE="$(tput setaf 4)"
BLUE_BG="$(tput setab 4)"
MAGENTA="$(tput setaf 5)"
MAGENTA_BG="$(tput setab 5)"
CYAN="$(tput setaf 6)"
CYAN_BG="$(tput setab 6)"
WHITE="$(tput setaf 7)"
WHITE_BG="$(tput setab 7)"
RESET="$(tput sgr0)"
BOLD="$(tput bold)"
UNDERLINE="$(tput smul)"
MYSTERY="$(tput setaf "$(awk 'BEGIN { srand(); printf("%d\n", 256 * rand()) }')")"

# Pointless things
banner() {
  get_fettlin="$(
    cat <<EOL

   █████████            █████       ███████████           █████     █████    ████   ███              ██
  ███░░░░░███          ░░███       ░░███░░░░░░█          ░░███     ░░███    ░░███  ░░░              ███
 ███     ░░░   ██████  ███████      ░███   █ ░   ██████  ███████   ███████   ░███  ████  ████████  ░░░ 
░███          ███░░███░░░███░       ░███████    ███░░███░░░███░   ░░░███░    ░███ ░░███ ░░███░░███     
░███    █████░███████   ░███        ░███░░░█   ░███████   ░███      ░███     ░███  ░███  ░███ ░███     
░░███  ░░███ ░███░░░    ░███ ███    ░███  ░    ░███░░░    ░███ ███  ░███ ███ ░███  ░███  ░███ ░███     
 ░░█████████ ░░██████   ░░█████     █████      ░░██████   ░░█████   ░░█████  █████ █████ ████ █████    
  ░░░░░░░░░   ░░░░░░     ░░░░░     ░░░░░        ░░░░░░     ░░░░░     ░░░░░  ░░░░░ ░░░░░ ░░░░ ░░░░░     
EOL
  )"

  awk 'BEGIN { srand(); printf("%d %d\n", 256 * rand(), 256 * rand()) }' |
    while read -r one two; do
      echo "${get_fettlin}" |
        sed "s/█/$(tput setab "${one}") ${RESET}/g" |
        sed "s/░/$(tput setab "${two}") ${RESET}/g"
    done
}

# Decision makers
choose_wisely() {
  select yn in "Yes" "No"; do
    case ${yn} in
    Yes) break ;;
    No)
      step_done "Very well"
      exit
      ;;
    esac
  done
}

# File helpers
append_to_file() {
  local text="$1"
  local file="$2"

  if ! grep -Fsq "${text}" "${file}"; then
    printf "\n%s\n" "${text}" >>"${file}"
  fi
}

# Output helpers
bold() {
  echo "${BOLD}$*${RESET}"
}

err() {
  echo "${RED}$*${RESET}"
}

mystery() {
  echo "${MYSTERY}$*${RESET}"
}

step() {
  echo
  echo "${BOLD}$*${RESET}"
}

step_done() {
  echo "${BOLD}$*${RESET}"
}

substep() {
  echo "${BLUE}➡ $*${RESET}"
}

substep_done() {
  echo "${GREEN}➡ $*${RESET}"
}

underline() {
  echo "${UNDERLINE}$*${RESET}"
}

info() {
  echo "${WHITE_BG}${BLACK}  $*  ${RESET}"
}

warn() {
  echo "${YELLOW}➡ $*${RESET}"
}

warn_bg() {
  echo "${RED_BG}${WHITE}  $*  ${RESET}"
}
